'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class register1

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''tx_nm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_nm As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tx_nik control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_nik As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tx_user control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_user As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tx_em control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_em As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cb_level control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_level As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''cb_dept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_dept As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''tx_telp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_telp As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tx_jabatan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_jabatan As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tx_pass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_pass As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''tx_pass2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_pass2 As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''bt_login control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bt_login As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''lb_hasil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_hasil As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
