'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class uc_menu

    '''<summary>
    '''divadmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents divadmin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''karyawan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents karyawan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents dept As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mn_materi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents mn_materi As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''bnk_soal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents bnk_soal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mn_quiz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents mn_quiz As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''nilai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents nilai As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
